# Generated by Django 2.2.4 on 2019-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ratings',
            name='movie_id',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.DeleteModel(
            name='Actors',
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='movie_id',
            field=models.ManyToManyField(to='imdb_api.Movie'),
        ),
        migrations.AddField(
            model_name='actor',
            name='movie_id',
            field=models.ManyToManyField(to='imdb_api.Movie'),
        ),
    ]
