# Generated by Django 2.2.4 on 2019-08-15 12:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0002_auto_20190815_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='movie_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='imdb_api.Movie'),
            preserve_default=False,
        ),
    ]
